### PR TITLE
Make AR transformer compatible with fork version

### PR DESCRIPTION
**Pull request by jchung01**
See dercodeKoenig/AdvancedRocketry#37 for details. Made the transformer more specific to original AR, which means you don't need to disable the patch in the configs to get AR-Reworked ASM code to work.

### CODE REVIEW

**Comment by kappa-maintainer** [comment]
Does the new fork have some more obvious characteristics (like a new class)?
Identify it from opcodes seems not a good idea in long term

**Comment by jchung01** [comment]
The transformer class is actually identical (before changes in the linked PR) between original AR and AR-Reworked, but for some reason the line numbers were different. I couldn't figure out why though.

> Identify it from opcodes seems not a good idea in long term
There would need to be exactly 2 `ICONST_0/ICONST_1` instructions in this block of code, so I think it should be relatively safe from incorrect injection. As is, the LineNumber check actually causes a crash in AR-Reworked's transformer, so I don't think this would be any worse.

**Comment by kappa-maintainer** [comment]
Merge it for now, I will check this fork later

**Comment by jchung01** [comment]
Oh I should probably clarify, this is to make the Fugue transformer **NOT** apply to AR-Reworked's ASM code once the other PR is merged. So the way to identify is only to determine if regular AR is being used, it will skip patching on AR-Reworked.

**Pull request merged**
